export { ClientCreateUpdateComponent } from './cliente/client-create-update/client-create-update.component';
export { ClienteListComponent } from './cliente/cliente-list/cliente-list.component';
export { ClientMainComponent } from './cliente/client-main/client-main.component';
export { MainComponent } from './main/main.component'; 
export { NotFoundComponent } from './not-found/not-found.component';
export { TicketMainComponent } from './ticket-main/ticket-main.component';
export { EmpresaParceiraMainComponent } from './empresa-parceira/empresa-parceira-main/empresa-parceira-main.component';
export { EmpresaParceiraCreateUpdateComponent } from './empresa-parceira/empresa-parceira-create-update/empresa-parceira-create-update.component';
export { EmpresaParceiraListComponent } from './empresa-parceira/empresa-parceira-list/empresa-parceira-list.component'; 