export { ClientCreateUpdateComponent } from './client-create-update/client-create-update.component';
export { ClientListComponent } from './client-list/client-list.component';
export { ClientMainComponent } from './client-main/client-main.component';
export { MainComponent } from './main/main.component'; 
export { NotFoundComponent } from './not-found/not-found.component';
export { TechnicianCreateUpdateComponent } from './technician-create-update/technician-create-update.component';
export { TechnicianListComponent } from './technician-list/technician-list.component';
export { TechnicianMainComponent } from './technician-main/technician-main.component';
export { TicketMainComponent } from './ticket-main/ticket-main.component';