export * from './client-create-update/client-create-update.component';
export * from './client-list/client-list.component';
export * from './client-main/client-main.component';
export * from './main/main.component';
export * from './not-found/not-found.component';
export * from './technician-create-update/technician-create-update.component';
export * from './technician-list/technician-list.component';
export * from './technician-main/technician-main.component';
export * from './ticket-main/ticket-main.component';